### ISSUE TITLE
update environment creation

### ISSUE THREAD

**Issue by anastassiavybornova** [mszell/bikenwgrowth#11]

**Comment by anastassiavybornova** [comment]
@mszell if the `growbikenet` env worked for you without warnings? -- we can close this one

**Comment by anastassiavybornova** [comment]
we also have a separate issue for adding manual installation instructions by command line: #15

**Comment by mszell** [comment]
Ok. done: https://github.com/mszell/bikenwgrowth/commit/4fe2a380110618073ce96bc0dd6b26504cdf98ea
