### ISSUE TITLE
Rename `query_checkcities.txt` to `query_checkcities.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [mszell/bikenwgrowth#6]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*
Also, it is the most widely used extension on GitHub, see https://github.com/users/FloEdelmann/projects/2/views/2

I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by FloEdelmann** [comment]
@mszell Would you accept a pull request?

**Comment by mszell** [comment]
Thx, resolved here: https://github.com/mszell/bikenwgrowth/commit/d0923c0ac5f87a76088cb0e9229371df22f400ff
